name: Publish Tweet of collection

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 16 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm run publishTweet
      env: 
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_OAUTH_TOKEN_CLIENT: ${{ secrets.TWITTER_OAUTH_TOKEN_CLIENT }}
        TWITTER_OAUTH_SECRET_CLIENT: ${{ secrets.TWITTER_OAUTH_SECRET_CLIENT }}
    - run: |
        git config user.name albertocruzluis
        git config user.email albertocruzluisdev@gmail.com
        git add ./data/*
        git commit -m "[bot] Publish Tweet of collection"
        git push origin master